+incdir+../include
../DUT/RTL/parameter.sv
../DUT/RTL/sfiforeq.sv
../DUT/RTL/sfifordata.sv 
../DUT/RTL/sfifowdata.sv 
../DUT/RTL/sfifobresp.sv 
../DUT/RTL/axi_transaction_controller.sv 
../DUT/RTL/arbiter.sv 
../DUT/RTL/counter.sv 
../DUT/RTL/decoder.sv 
../DUT/RTL/apb_master.sv 
../DUT/RTL/x2p_top.sv 
./tb.sv
